const ProjectList = [
  {
    id: 1,
    title: "Startup Marquee",
    href: "https://headache-helpers-unite.vercel.app/",
    date: "Mar 16, 2020",
    datetime: "2020-03-16",
    category: { name: "ai" },
    imageUrl: "/images/vibe-two.png",
    preview:
      "Helping Startup companies and Entrepreneurs bySolving their Vibe coding issues.",
    author: {
      name: "PublicTrades (Startup Marquee)",
      imageUrl: "/images/vibe-two.png",
      href: "#",
      status: "launched",
    },
    readingLength: "6 min",
  },
  {
    id: 2,
    title: "VoiseAI",
    href: "https://skill-forge-ai-hub.vercel.app/",
    date: "Mar 16, 2020",
    datetime: "2020-03-16",
    category: { name: "ai" },
    imageUrl: "/images/voiseai-image.png",
    preview:
      "Using artificial intelligence to teach how to apply AI in both your professional and personal life.",
    author: {
      name: "PublicTrades (VoiseAI)",
      imageUrl: "/images/voiseai-image.png",
      href: "#",
      status: "In development",
    },
    readingLength: "6 min",
  },
  {
    id: 3,
    title: "reBlug",
    href: "https://reblug.com",
    date: "Mar 16, 2020",
    datetime: "2020-03-16",
    category: { name: "marketing" },
    imageUrl: "/images/reblug.png",
    preview:
      "Providing a unified ecosystem where brands, marketers and bloggers can connect.",
    author: {
      name: "PublicTrades (reBlug)",
      imageUrl: "/images/reblug.png",
      href: "#",
      status: "In development",
    },
    readingLength: "6 min",
  },
  {
    id: 4,
    title: "reBlug",
    href: "https://reblug.com",
    date: "Mar 16, 2020",
    datetime: "2020-03-16",
    category: { name: "ai" },
    imageUrl: "/images/reblug.png",
    preview:
      "Providing a unified ecosystem where brands, marketers and bloggers can connect.",
    author: {
      name: "PublicTrades (reBlug)",
      imageUrl: "/images/reblug.png",
      href: "#",
      status: "In development",
    },
    readingLength: "1 min",
  },
  {
    id: 5,
    title: "reBlug",
    href: "https://reblug.com",
    date: "Mar 16, 2020",
    datetime: "2020-03-16",
    category: { name: "consumer" },
    imageUrl: "/images/reblug.png",
    preview:
      "Providing a unified ecosystem where brands, marketers and bloggers can connect.",
    author: {
      name: "PublicTrades (reBlug)",
      imageUrl: "/images/reblug.png",
      href: "#",
      status: "In development",
    },
    readingLength: "1 min",
  },
  {
    id: 6,
    title: "Plain Network",
    href: "https://plain-mobile.vercel.app/",
    date: "Sep 29, 2024",
    datetime: "2020-03-16",
    category: { name: "consumer" },
    imageUrl: "/images/plain.png",
    preview:
      "AI powered private mobile network for wireless products and services .",
    author: {
      name: "PublicTrades (plain)",
      imageUrl: "/images/reblug.png",
      href: "#",
      status: "In development",
    },
    readingLength: "1 min",
  },
  {
    id: 7,
    title: "Plain Network",
    href: "https://plain-mobile.vercel.app/",
    date: "Sep 29, 2024",
    datetime: "2020-03-16",
    category: { name: "ai" },
    imageUrl: "/images/plain.png",
    preview:
      "AI powered private mobile network for wireless products and services .",
    author: {
      name: "PublicTrades (plain)",
      imageUrl: "/images/reblug.png",
      href: "#",
      status: "In development",
    },
    readingLength: "1 min",
  },
  {
    id: 8,
    title: "CyberPOV",
    href: "https://cyber-eye-witness-defense.vercel.app/",
    date: "Dec 3, 2024",
    datetime: "2020-03-16",
    category: { name: "security" },
    imageUrl: "/images/cyberpov.png",
    preview:
      "AI-powered cloud security tool for real-time threat detection and prevention",
    author: {
      name: "PublicTrades (CyberPOV)",
      imageUrl: "/images/cyberpov.png",
      href: "#",
      status: "In development",
    },
    readingLength: "1 min",
  },
  {
    id: 9,
    title: "Stream Wire",
    href: "https://streaming-publictrades-projects.vercel.app",
    date: "Dec 20, 2024",
    datetime: "2020-03-16",
    category: { name: "consumer" },
    imageUrl: "/images/streamwire.png",
    preview:
      "Helping creators to generate and stream AI-powered video content.",
    author: {
      name: "PublicTrades (scorpy)",
      imageUrl: "/images/streamwire.png",
      href: "#",
      status: "In development",
    },
    readingLength: "1 min",
  },
];

export default ProjectList;
